# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20170228_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='convo_audio',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='convo_author',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='convo_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_embed',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
