# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:43
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20170301_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='convo_text',
            field=django_markdown.models.MarkdownField(blank=True, null=True),
        ),
    ]
