# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20170301_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='convo_with',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
